apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: api
  namespace: argocd

spec:
  project: default
  source:
    repoUrl: git@github.com/brxlx/nlw-unite.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true