apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment
  labels:
    app: api

spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: danielrodriguess/nlw.service.passin
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: password

            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: url
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi
