apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - name: api-service
    port: 80
    targetPort: 3333
    protocol: TCP
