version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pass-in-api
    restart: unless-stopped
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}?schema=public