version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pass-in-api
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://admin:admin@host.docker.internal:5432/nlw-unite?schema=public
      - API_BASE_URL=http://localhost:3333